import {beforeEach,it,expect,vi} from 'vitest';
const callbacks=vi.hoisted(()=>({next:null as null|((snap:any)=>void),error:null as null|(()=>void),stop:vi.fn()}));
vi.mock('@/services/firebase',()=>({getFirebaseFirestore:()=>({})}));
vi.mock('firebase/firestore',async original=>({...await original<typeof import('firebase/firestore')>(),collection:()=>({}),onSnapshot:(_ref:unknown,_options:unknown,next:(snap:any)=>void,error:()=>void)=>{callbacks.next=next;callbacks.error=error;return callbacks.stop;}}));
import {recurringRepository} from './recurringRepository';
import {useAuthStore} from './authStore';
const signIn=(uid:string)=>useAuthStore.setState({user:{uid,email:null,displayName:null,emailVerified:true}});
beforeEach(()=>{callbacks.stop.mockClear();signIn('a');});
it('ignores callbacks from the previous account immediately',()=>{const notify=vi.fn(),stop=recurringRepository.observe('a',notify);callbacks.next!({docs:[],metadata:{fromCache:false}});expect(notify).toHaveBeenCalledTimes(1);signIn('b');callbacks.next!({docs:[],metadata:{fromCache:false}});callbacks.error!();expect(notify).toHaveBeenCalledTimes(1);stop();expect(callbacks.stop).toHaveBeenCalledTimes(1);});
it('cleanup rejects late snapshots even if the same account remounts',()=>{const notify=vi.fn(),stop=recurringRepository.observe('a',notify);stop();callbacks.next!({docs:[],metadata:{fromCache:false}});callbacks.error!();expect(notify).not.toHaveBeenCalled();});
